# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
